#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{March 2016}"                                               << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;

  int termsAtATime = 1;
  int linesPrinted = 0;
  int termsToPrint = 1;
  int totalLinesToPrint = 1;

  /**********************/
  /* Page 1 starts here */
  /**********************/

  vector<Term> xTerms;
  xTerms.push_back(Term("lambda*(-4*a_17)*ABA"));
  xTerms.push_back(Term("lambda*(-12*a_14*a_123)*BBABA"));
  Polynomial x(xTerms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  /* x.groupTerms(); */
  termsToPrint = x.getTerms().size()+x.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$X$ & = & $";
      else
	texFile << " & & $";
      x.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 1 ends here */
  /********************/

  texFile << "\\newpage" << endl << endl;

  /**********************/
  /* Page 2 starts here */
  /**********************/

  vector<Term> yTerms;
  yTerms.push_back(Term("lambda*(a_20)*BB"));
  yTerms.push_back(Term("lambda*(-1*a_20)*AA"));
  yTerms.push_back(Term("lambda*(a_31)*BBBA"));
  yTerms.push_back(Term("lambda*(-1*a_31)*BAAA"));
  yTerms.push_back(Term("lambda*(a_40)*BBBB"));
  yTerms.push_back(Term("lambda*(a_40)*AAAA"));
  yTerms.push_back(Term("lambda^2*(a_10020)*BB"));
  yTerms.push_back(Term("lambda^2*(-1*a_10020)*AA"));
  yTerms.push_back(Term("lambda^2*(a_10031)*BBBA"));
  yTerms.push_back(Term("lambda^2*(-1*a_10031)*BAAA"));
  yTerms.push_back(Term("lambda^2*(a_10040)*BBBB"));
  yTerms.push_back(Term("lambda^2*(-1*a_10040)*AAAA"));
  yTerms.push_back(Term("lambda^2*(a_10042)*BBBBAA"));
  yTerms.push_back(Term("lambda^2*(-1*a_10042)*BBAAAA"));
  yTerms.push_back(Term("lambda^2*(a_10060)*BBBBBB"));
  yTerms.push_back(Term("lambda^2*(-1*a_10060)*AAAAAA"));
  Polynomial y(yTerms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  y.groupTerms();
  termsToPrint = y.getTerms().size()+y.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$Y$ & = & $";
      else
	texFile << " & & $";
      y.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;



  vector<Term> h0Terms;
  h0Terms.push_back(Term("BA"));
  Polynomial h0(h0Terms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  h0.groupTerms();
  termsToPrint = h0.getTerms().size()+h0.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$H_{0}$ & = & $";
      else
	texFile << " & & $";
      h0.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;




  Polynomial CommutatorResult = y.commutedWith(h0);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  CommutatorResult.groupTerms();
  termsToPrint = CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted == 0) {
	texFile << "$[Y,H_{0}]$ & = & $";
      } else {
	texFile << " & & $";
      }
      CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 2 ends here */
  /********************/

  texFile << "\\newpage" << endl << endl;

  /**********************/
  /* Page 3 starts here */
  /**********************/

  vector<Term> L20Terms;
  L20Terms.push_back(Term("BB"));
  L20Terms.push_back(Term("(-1)*AA"));
  Polynomial L20(L20Terms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  L20.groupTerms();
  termsToPrint = L20.getTerms().size()+L20.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$L^{2}_{0}$ & = & $";
      else
	texFile << " & & $";
      L20.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;


  vector<Term> L31Terms;
  L31Terms.push_back(Term("BBBA"));
  L31Terms.push_back(Term("(-1)*BAAA"));
  Polynomial L31(L31Terms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  L31.groupTerms();
  termsToPrint = L31.getTerms().size()+L31.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$L^{3}_{1}$ & = & $";
      else
	texFile << " & & $";
      L31.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;


  vector<Term> L31BarTerms;
  L31BarTerms.push_back(Term("BBBA"));
  L31BarTerms.push_back(Term("BAAA"));
  Polynomial L31Bar(L31BarTerms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  L31Bar.groupTerms();
  termsToPrint = L31Bar.getTerms().size()+L31Bar.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$\\bar{L}^{3}_{1}$ & = & $";
      else
	texFile << " & & $";
      L31Bar.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  Polynomial Commutator_2_3_3 = L20.commutedWith(L31.commutedWith(L31Bar));

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  Commutator_2_3_3.groupTerms();
  termsToPrint = Commutator_2_3_3.getTerms().size()+Commutator_2_3_3.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted == 0) {
  	texFile << "$[L^{2}_{0},[L^{3}_{1},\\bar{L}^{3}_{1}]]$ & = & $";
      } else {
  	texFile << " & & $";
      }
      Commutator_2_3_3.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 3 ends here */
  /********************/

  texFile << "\\end{document}" << endl;

  return 0;
}
