#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic_12.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{March 2011}"                                                 << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;

  vector<Term> xTerms;
  xTerms.push_back(Term("lambda*(17/3*a_1)*BBBB"));
  xTerms.push_back(Term("lambda*(-4/3*a_1)*AAAA"));
  xTerms.push_back(Term("lambda*(a_2)*BBBA"));
  xTerms.push_back(Term("lambda*(-1*a_2)*BAAA"));
  xTerms.push_back(Term("lambda*(a_3)*BB"));
  xTerms.push_back(Term("lambda*(-1*a_3)*AA"));
  Polynomial x(xTerms);

  x.print();
  cout << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  int termsAtATime = 1;
  int linesPrinted = 0;
  
  x.groupTerms();
  texFile << "$X$ & = & $";
  x.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  int termsToPrint = x.getTerms().size()+x.getDoubleTerms().size();
  int totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      x.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  vector<Term> h0Terms;
  h0Terms.push_back(Term("BA"));
  Polynomial h0(h0Terms);

  Polynomial CommutatorResult = h0.commutedWith(x);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  termsAtATime = 1;
  linesPrinted = 0;
  
  CommutatorResult.groupTerms();
  texFile << "$[-X,H_{0}]$ & = & $";
  CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  Polynomial SecondCommutatorResult  = CommutatorResult.commutedWith(x);
  /* vector<Term> OneHalfTermVect; */
  /* OneHalfTermVect.push_back(Term("(0.5)")); */
  /* Polynomial OneHalf(OneHalfTermVect); */
  /* SecondCommutatorResult *= OneHalf; */

  termsAtATime = 1;
  linesPrinted = 0;
  
  SecondCommutatorResult.groupTerms();
  texFile << "$[-X,[-X,H_{0}]]$ & = & $";
  SecondCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = SecondCommutatorResult.getTerms().size()+SecondCommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      SecondCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  Polynomial ThirdCommutatorResult  = SecondCommutatorResult.commutedWith(x);

  termsAtATime = 1;
  linesPrinted = 0;
  
  ThirdCommutatorResult.groupTerms();
  texFile << "$[-X,[-X,[-X,H_{0}]]]$ & = & $";
  ThirdCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = ThirdCommutatorResult.getTerms().size()+ThirdCommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      ThirdCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  /* texFile << "$[-X,H_{0}] + \\frac{1}{2!}[-X,[-X,H_{0}]]$" << endl; */

  /* texFile << "\\begin{table}[!hp]"                                                << endl; */
  /* texFile << "\\begin{center}"                                                    << endl; */
  /* texFile << "\\begin{tabular}{rcl}"                                              << endl; */

  /* Polynomial PreFinalComputation  = CommutatorResult+SecondCommutatorResult; */

  /* termsAtATime = 1; */
  /* linesPrinted = 0; */
  
  /* PreFinalComputation.groupTerms(); */
  /* texFile << " & = & $"; */
  /* PreFinalComputation.printTex(texFile,termsAtATime,linesPrinted++); */
  /* texFile << "$ \\\\" << endl; */
  
  /* termsToPrint = PreFinalComputation.getTerms().size()+PreFinalComputation.getDoubleTerms().size(); */
  /* totalLinesToPrint = termsToPrint/termsAtATime; */
  /* if (termsToPrint%termsAtATime != 0) totalLinesToPrint++; */
  /* while (linesPrinted < totalLinesToPrint) */
  /*   { */
  /*     texFile << "                                           &   & $"; */
  /*     PreFinalComputation.printTex(texFile,termsAtATime,linesPrinted++); */
  /*     texFile << "$"; */
  /*     texFile << " \\\\" << endl; */
  /*   } */

  /* texFile << "\\end{tabular}"                                              << endl; */
  /* texFile << "\\end{center}"                                               << endl; */
  /* texFile << "\\end{table}"                                                << endl << endl;; */


  /* texFile << "\\newpage" << endl << endl; */

  /* texFile << "\\begin{table}[!hp]"                                                << endl; */
  /* texFile << "\\begin{center}"                                                    << endl; */
  /* texFile << "\\begin{tabular}{rcl}"                                              << endl; */


  /* Polynomial FinalComputation     = h4-PreFinalComputation; */

  /* termsAtATime = 1; */
  /* linesPrinted = 0; */
  
  /* FinalComputation.groupTerms(); */
  /* texFile << "$H_{4} - U^{\\dagger}H_{0}U$ & = & $\\Lambda_{4}$ \\\\" << endl; */
  /* texFile << "                             &   & \\\\" << endl; */
  /* texFile << "                             & = & $\\frac{\\lambda}{4}(A+B)^{4} - \\left([-X,H_{0}] + \\frac{1}{2!}[-X,[-X,H_{0}]]\\right)$ \\\\" << endl; */
  /* texFile << "                             &   & \\\\" << endl; */
  /* texFile << "                             & = & $"; */
  /* FinalComputation.printTex(texFile,termsAtATime,linesPrinted++); */
  /* texFile << "$ \\\\" << endl; */
  
  /* termsToPrint = FinalComputation.getTerms().size()+FinalComputation.getDoubleTerms().size(); */
  /* totalLinesToPrint = termsToPrint/termsAtATime; */
  /* if (termsToPrint%termsAtATime != 0) totalLinesToPrint++; */
  /* while (linesPrinted < totalLinesToPrint) */
  /*   { */
  /*     texFile << " & & $"; */
  /*     FinalComputation.printTex(texFile,termsAtATime,linesPrinted++); */
  /*     texFile << "$"; */
  /*     texFile << " \\\\" << endl; */
  /*   } */

  /* texFile << "\\end{tabular}"                                              << endl; */
  /* texFile << "\\end{center}"                                               << endl; */
  /* texFile << "\\end{table}"                                                << endl << endl;; */


  texFile << "\\end{document}" << endl;

  return 0;
}
