#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic_1.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{March 2011}"                                                 << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;
									          
  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;
  texFile << "\\textbf{Typed in by hand} & & \\textbf{Computed by machine} \\\\"  << endl;
  texFile << "\\hline"                                                            << endl;

  vector<Term> h0Terms;
  h0Terms.push_back(Term("BA"));
  Polynomial h0(h0Terms);

  vector<Term> xTerms;
  xTerms.push_back(Term("(a_5)*BBBB"));
  xTerms.push_back(Term("(a_5)*AAAA"));
  xTerms.push_back(Term("(a_6)*BBBA"));
  xTerms.push_back(Term("(a_6)*BAAA"));
  xTerms.push_back(Term("(a_7)*BB"));
  xTerms.push_back(Term("(a_7)*AA"));
  xTerms.push_back(Term("(a_8)*BBBB"));
  xTerms.push_back(Term("(-1*a_8)*AAAA"));
  xTerms.push_back(Term("(a_9)*BBBA"));
  xTerms.push_back(Term("(-1*a_9)*BAAA"));
  xTerms.push_back(Term("(a_10)*BB"));
  xTerms.push_back(Term("(-1*a_10)*AA"));
  Polynomial x(xTerms);

  int yet = 0;
  vector<Term> h4Terms;
  h4Terms.push_back(Term("A"));
  h4Terms.push_back(Term("B"));
  Polynomial h4(h4Terms);
  h4^=4;
  vector<Term> lambdaTermOnly;
  lambdaTermOnly.push_back(Term("lambda*(0.25)"));
  Polynomial lambdaPolynomialOnly(lambdaTermOnly);
  h4*=lambdaPolynomialOnly;

  int termsAtATime = 2;
  int linesPrinted = 0;

  texFile << "$H_{4}$ & = & $";
  h4.groupTerms();
  h4.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;

  int termsToPrint = h4.getTerms().size()+h4.getDoubleTerms().size();
  int totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      h4.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << " & & \\\\" << endl;

  texFile << "$[H_0,H_4]$ & = & ";
  texFile << "$[B{\\cdot}A,{\\lambda}{\\cdot}(\\frac{A+B}{\\sqrt{2}})^{4}]$ \\\\" << endl;
  texFile << " & = & $";
  Polynomial commutator = h0.commutedWith(h4);
  commutator.groupTerms();
  commutator.printTex(texFile);
  texFile << "$ \\\\" << endl;


  termsAtATime = 1;
  linesPrinted = 0;

  texFile << "$[H_{0},X]$ & = & $";
  Polynomial HammardCommutator = h0.commutedWith(x);
  HammardCommutator.groupTerms();
  HammardCommutator.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = HammardCommutator.getTerms().size()+HammardCommutator.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      HammardCommutator.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << " & & \\\\" << endl;







  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;;

  texFile << "\\end{document}" << endl;

  return 0;
}
