#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{January 2015}"                                               << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;

  vector<Term> xTerms;
  xTerms.push_back(Term("lambda*(17/3*a_1)*BBBB"));
  xTerms.push_back(Term("lambda*(-4/3*a_1)*AAAA"));
  xTerms.push_back(Term("lambda*(a_2)*BBBA"));
  xTerms.push_back(Term("lambda*(-1*a_2)*BAAA"));
  xTerms.push_back(Term("lambda*(a_3)*BB"));
  xTerms.push_back(Term("lambda*(-1*a_3)*AA"));
  Polynomial x(xTerms);

  x.print();
  cout << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  int termsAtATime = 1;
  int linesPrinted = 0;
  
  x.groupTerms();
  texFile << "$X$ & = & $";
  x.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  int termsToPrint = x.getTerms().size()+x.getDoubleTerms().size();
  int totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      x.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  vector<Term> h0Terms;
  h0Terms.push_back(Term("BA"));
  Polynomial h0(h0Terms);

  Polynomial CommutatorResult = h0.commutedWith(x);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  termsAtATime = 1;
  linesPrinted = 0;
  
  CommutatorResult.groupTerms();
  texFile << "$[-X,H_{0}]$ & = & $";
  CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\end{document}" << endl;

  return 0;
}
