#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{March 2016}"                                               << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;

  int termsAtATime = 1;
  int linesPrinted = 0;
  int termsToPrint = 1;
  int totalLinesToPrint = 1;

  /**********************/
  /* Page 1 starts here */
  /**********************/

  vector<Term> xTerms;
  xTerms.push_back(Term("lambda*(-1*a_17)*ABA"));
  xTerms.push_back(Term("lambda*(-12*a_14*a_123)*BBABA"));
  Polynomial x(xTerms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  /* x.groupTerms(); */
  termsToPrint = x.getTerms().size()+x.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$X$ & = & $";
      else
	texFile << " & & $";
      x.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 1 ends here */
  /********************/

  texFile << "\\newpage" << endl << endl;

  /**********************/
  /* Page 2 starts here */
  /**********************/

  vector<Term> x2Terms;
  x2Terms.push_back(Term("lambda*(-1*a_17)*ABA"));
  x2Terms.push_back(Term("lambda*(-12*a_14*a_123)*BBABA"));
  Polynomial x2(x2Terms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  x2.groupTerms();
  termsToPrint = x2.getTerms().size()+x2.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$X$ & = & $";
      else
	texFile << " & & $";
      x2.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 2 ends here */
  /********************/

  texFile << "\\newpage" << endl << endl;

  /**********************/
  /* Page 3 starts here */
  /**********************/

  vector<Term> yTerms;
  yTerms.push_back(Term("lambda*(a_20)*BB"));
  yTerms.push_back(Term("lambda*(-1*a_20)*AA"));
  yTerms.push_back(Term("lambda*(a_30)*BBBA"));
  yTerms.push_back(Term("lambda*(-1*a_30)*BAAA"));
  yTerms.push_back(Term("lambda*(a_40)*BBBB"));
  yTerms.push_back(Term("lambda*(a_40)*AAAA"));
  yTerms.push_back(Term("lambda^2*(a_10020)*BB"));
  yTerms.push_back(Term("lambda^2*(-1*a_10020)*AA"));
  yTerms.push_back(Term("lambda^2*(a_10031)*BBBA"));
  yTerms.push_back(Term("lambda^2*(-1*a_10031)*BAAA"));
  yTerms.push_back(Term("lambda^2*(a_10040)*BBBB"));
  yTerms.push_back(Term("lambda^2*(-1*a_10040)*AAAA"));
  yTerms.push_back(Term("lambda^2*(a_10042)*BBBBAA"));
  yTerms.push_back(Term("lambda^2*(-1*a_10042)*BBAAAA"));
  yTerms.push_back(Term("lambda^2*(a_10060)*BBBBBB"));
  yTerms.push_back(Term("lambda^2*(-1*a_10060)*AAAAAA"));
  Polynomial y(yTerms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  y.groupTerms();
  termsToPrint = y.getTerms().size()+y.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$Y$ & = & $";
      else
	texFile << " & & $";
      y.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 3 ends here */
  /********************/

  texFile << "\\newpage" << endl << endl;

  /**********************/
  /* Page 4 starts here */
  /**********************/

  vector<Term> zTerms;
  zTerms.push_back(Term("lambda*(-1*a_17)*ABA"));
  zTerms.push_back(Term("lambda*(-12*a_14*a_123)*BBABA"));
  Polynomial z(zTerms);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  linesPrinted = 0;
  
  /* z.groupTerms(); */
  termsToPrint = z.getTerms().size()+z.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;

  while (linesPrinted < totalLinesToPrint)
    {
      if (linesPrinted==0) 
	texFile << "$Z$ & = & $";
      else
	texFile << " & & $";
      z.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 3 ends here */
  /********************/

  texFile << "\\newpage" << endl << endl;

  /**********************/
  /* Page 5 starts here */
  /**********************/

  vector<Term> h0Terms;
  h0Terms.push_back(Term("BA"));
  Polynomial h0(h0Terms);

  Polynomial CommutatorResult = h0.commutedWith(x);

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  termsAtATime = 1;
  linesPrinted = 0;
  
  CommutatorResult.groupTerms();
  texFile << "$[-X,H_{0}]$ & = & $";
  CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  /********************/
  /* Page 5 ends here */
  /********************/

  texFile << "\\end{document}" << endl;

  return 0;
}
