#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic_11.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{March 2011}"                                                 << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;
									          
  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;
  /* texFile << "\\textbf{Typed in by hand} & & \\textbf{Computed by machine} \\\\"  << endl; */
  /* texFile << "\\hline"                                                            << endl; */


  vector<Term> xTerms;
  /* xTerms.push_back(Term("(a_0)")); */
  /* xTerms.push_back(Term("(a_1)*BA")); */

  /* xTerms.push_back(Term("lambda*(a_2)")); */
  /* xTerms.push_back(Term("lambda*(a_3)*BA")); */
  /* xTerms.push_back(Term("lambda*(a_4)*BBAA")); */

  /* xTerms.push_back(Term("lambda*(a_5)*BBBB")); */
  /* xTerms.push_back(Term("lambda*(a_5)*AAAA")); */
  /* xTerms.push_back(Term("lambda*(a_6)*BBBA")); */
  /* xTerms.push_back(Term("lambda*(a_6)*BAAA")); */
  /* xTerms.push_back(Term("lambda*(a_7)*BB")); */
  /* xTerms.push_back(Term("lambda*(a_7)*AA")); */

  xTerms.push_back(Term("lambda*(a_8)*BBBB"));
  xTerms.push_back(Term("lambda*(-1*a_8)*AAAA"));
  xTerms.push_back(Term("lambda*(a_9)*BBBA"));
  xTerms.push_back(Term("lambda*(-1*a_9)*BAAA"));
  xTerms.push_back(Term("lambda*(a_10)*BB"));
  xTerms.push_back(Term("lambda*(-1*a_10)*AA"));

  /* xTerms.push_back(Term("lambda^2*(a_11)")); */
  /* xTerms.push_back(Term("lambda^2*(a_12)*BA")); */
  /* xTerms.push_back(Term("lambda^2*(a_13)*BBAA")); */
  /* xTerms.push_back(Term("lambda^2*(a_14)*BBBAAA")); */

  xTerms.push_back(Term("lambda^2*(a_15)*BBBBBB"));
  xTerms.push_back(Term("lambda^2*(a_15)*AAAAAA"));
  xTerms.push_back(Term("lambda^2*(a_16)*BBBBBA"));
  xTerms.push_back(Term("lambda^2*(a_16)*BAAAAA"));
  xTerms.push_back(Term("lambda^2*(a_17)*BBBBAA"));
  xTerms.push_back(Term("lambda^2*(a_17)*BBAAAA"));
  xTerms.push_back(Term("lambda^2*(a_18)*BBBB"));
  xTerms.push_back(Term("lambda^2*(a_18)*AAAA"));
  xTerms.push_back(Term("lambda^2*(a_19)*BBBA"));
  xTerms.push_back(Term("lambda^2*(a_19)*BAAA"));
  xTerms.push_back(Term("lambda^2*(a_20)*BB"));
  xTerms.push_back(Term("lambda^2*(a_20)*AA"));

  xTerms.push_back(Term("lambda^2*(a_21)*BBBBBB"));
  xTerms.push_back(Term("lambda^2*(-1*a_21)*AAAAAA"));
  xTerms.push_back(Term("lambda^2*(a_22)*BBBBBA"));
  xTerms.push_back(Term("lambda^2*(-1*a_22)*BAAAAA"));
  xTerms.push_back(Term("lambda^2*(a_23)*BBBBAA"));
  xTerms.push_back(Term("lambda^2*(-1*a_23)*BBAAAA"));
  xTerms.push_back(Term("lambda^2*(a_24)*BBBB"));
  xTerms.push_back(Term("lambda^2*(-1*a_24)*AAAA"));
  xTerms.push_back(Term("lambda^2*(a_25)*BBBA"));
  xTerms.push_back(Term("lambda^2*(-1*a_25)*BAAA"));
  xTerms.push_back(Term("lambda^2*(a_26)*BB"));
  xTerms.push_back(Term("lambda^2*(-1*a_26)*AA"));

  /* xTerms.push_back(Term("lambda^3*(a_27)")); */
  /* xTerms.push_back(Term("lambda^3*(a_28)*BA")); */
  /* xTerms.push_back(Term("lambda^3*(a_29)*BBAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_30)*BBBAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_31)*BBBBAAAA")); */

  /* xTerms.push_back(Term("lambda^3*(a_32)*BBBBBBBB")); */
  /* xTerms.push_back(Term("lambda^3*(a_32)*AAAAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_33)*BBBBBBBA")); */
  /* xTerms.push_back(Term("lambda^3*(a_33)*BAAAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_34)*BBBBBBAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_34)*BBAAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_35)*BBBBBAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_35)*BBBAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_36)*BBBBBB")); */
  /* xTerms.push_back(Term("lambda^3*(a_36)*AAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_37)*BBBBBA")); */
  /* xTerms.push_back(Term("lambda^3*(a_37)*BAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_38)*BBBBAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_38)*BBAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_39)*BBBB")); */
  /* xTerms.push_back(Term("lambda^3*(a_39)*AAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_40)*BBBA")); */
  /* xTerms.push_back(Term("lambda^3*(a_40)*BAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_41)*BB")); */
  /* xTerms.push_back(Term("lambda^3*(a_41)*AA")); */
  /* xTerms.push_back(Term("lambda^3*(a_42)*BBBBBBBB")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_42)*AAAAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_43)*BBBBBBBA")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_43)*BAAAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_44)*BBBBBBAA")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_44)*BBAAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_45)*BBBBBAAA")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_45)*BBBAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_46)*BBBBBB")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_46)*AAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_47)*BBBBBA")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_47)*BAAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_48)*BBBBAA")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_48)*BBAAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_49)*BBBB")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_49)*AAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_50)*BBBA")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_50)*BAAA")); */
  /* xTerms.push_back(Term("lambda^3*(a_51)*BB")); */
  /* xTerms.push_back(Term("lambda^3*(-1*a_51)*AA")); */
  Polynomial x(xTerms);

  vector<Term> h4Terms;
  h4Terms.push_back(Term("A"));
  h4Terms.push_back(Term("B"));
  Polynomial h4(h4Terms);
  h4^=4;
  vector<Term> lambdaOverFourTerm;
  lambdaOverFourTerm.push_back(Term("lambda*(0.25)"));
  Polynomial lambdaOverFour(lambdaOverFourTerm);
  h4*=lambdaOverFour;
  h4.groupTerms();

  int termsAtATime = 1;
  int linesPrinted = 0;
  
  h4.groupTerms();
  texFile << "$\\frac{\\lambda}{4}(A+B)^{4}$ & = & $";
  h4.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  int termsToPrint = h4.getTerms().size()+h4.getDoubleTerms().size();
  int totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << "                               &   & $";
      h4.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  vector<Term> h0Terms;
  h0Terms.push_back(Term("BA"));
  Polynomial h0(h0Terms);

  Polynomial CommutatorResult = h0.commutedWith(x);

  termsAtATime = 1;
  linesPrinted = 0;
  
  CommutatorResult.groupTerms();
  texFile << "$[-X,H_{0}]$ & = & $";
  CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  Polynomial SecondCommutatorResult  = CommutatorResult.commutedWith(x);
  vector<Term> OneHalfTermVect;
  OneHalfTermVect.push_back(Term("(0.5)"));
  Polynomial OneHalf(OneHalfTermVect);
  SecondCommutatorResult *= OneHalf;

  termsAtATime = 1;
  linesPrinted = 0;
  
  SecondCommutatorResult.groupTerms();
  texFile << "$\\frac{1}{2!}[-X,[-X,H_{0}]]$ & = & $";
  SecondCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = SecondCommutatorResult.getTerms().size()+SecondCommutatorResult.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      SecondCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;

  texFile << "\\newpage" << endl << endl;

  /* texFile << "\\begin{table}[!hp]"                                                << endl; */
  /* texFile << "\\begin{center}"                                                    << endl; */
  /* texFile << "\\begin{tabular}{rcl}"                                              << endl; */

  /* Polynomial ThirdCommutatorResult  = SecondCommutatorResult.commutedWith(x); */
  /* vector<Term> TwoVect; */
  /* TwoVect.push_back(Term("(2)")); */
  /* Polynomial Two(TwoVect); */
  /* ThirdCommutatorResult *= Two; */
  /* /\* vector<Term> OneSixthTermVect; *\/ */
  /* /\* OneSixthTermVect.push_back(Term("(0.16666666667)")); *\/ */
  /* /\* Polynomial OneSixth(OneSixthTermVect); *\/ */
  /* /\* ThirdCommutatorResult *= OneSixth; *\/ */

  /* termsAtATime = 1; */
  /* linesPrinted = 0; */
  
  /* ThirdCommutatorResult.groupTerms(); */
  /* /\* texFile << "$\\frac{1}{3!}[-X,[-X,[-X,H_{0}]]]$ & = & $"; *\/ */
  /* texFile << "$[-X,[-X,[-X,H_{0}]]]$ & = & $"; */
  /* ThirdCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++); */
  /* texFile << "$ \\\\" << endl; */
  
  /* termsToPrint = ThirdCommutatorResult.getTerms().size()+ThirdCommutatorResult.getDoubleTerms().size(); */
  /* totalLinesToPrint = termsToPrint/termsAtATime; */
  /* if (termsToPrint%termsAtATime != 0) totalLinesToPrint++; */
  /* while (linesPrinted < totalLinesToPrint) */
  /*   { */
  /*     texFile << " & & $"; */
  /*     ThirdCommutatorResult.printTex(texFile,termsAtATime,linesPrinted++); */
  /*     texFile << "$"; */
  /*     texFile << " \\\\" << endl; */
  /*   } */

  /* texFile << "\\end{tabular}"                                              << endl; */
  /* texFile << "\\end{center}"                                               << endl; */
  /* texFile << "\\end{table}"                                                << endl << endl; */

  /* texFile << "\\newpage" << endl << endl; */

  texFile << "$[-X,H_{0}] + \\frac{1}{2!}[-X,[-X,H_{0}]]$" << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;

  Polynomial PreFinalComputation  = CommutatorResult+SecondCommutatorResult;

  termsAtATime = 1;
  linesPrinted = 0;
  
  PreFinalComputation.groupTerms();
  texFile << " & = & $";
  PreFinalComputation.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = PreFinalComputation.getTerms().size()+PreFinalComputation.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << "                                           &   & $";
      PreFinalComputation.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;;


  texFile << "\\newpage" << endl << endl;

  texFile << "\\begin{table}[!hp]"                                                << endl;
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{tabular}{rcl}"                                              << endl;


  Polynomial FinalComputation     = h4-PreFinalComputation;

  termsAtATime = 1;
  linesPrinted = 0;
  
  FinalComputation.groupTerms();
  texFile << "$H_{4} - U^{\\dagger}H_{0}U$ & = & $\\Lambda_{4}$ \\\\" << endl;
  texFile << "                             &   & \\\\" << endl;
  texFile << "                             & = & $\\frac{\\lambda}{4}(A+B)^{4} - \\left([-X,H_{0}] + \\frac{1}{2!}[-X,[-X,H_{0}]]\\right)$ \\\\" << endl;
  texFile << "                             &   & \\\\" << endl;
  texFile << "                             & = & $";
  FinalComputation.printTex(texFile,termsAtATime,linesPrinted++);
  texFile << "$ \\\\" << endl;
  
  termsToPrint = FinalComputation.getTerms().size()+FinalComputation.getDoubleTerms().size();
  totalLinesToPrint = termsToPrint/termsAtATime;
  if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
  while (linesPrinted < totalLinesToPrint)
    {
      texFile << " & & $";
      FinalComputation.printTex(texFile,termsAtATime,linesPrinted++);
      texFile << "$";
      texFile << " \\\\" << endl;
    }

  texFile << "\\end{tabular}"                                              << endl;
  texFile << "\\end{center}"                                               << endl;
  texFile << "\\end{table}"                                                << endl << endl;;


  texFile << "\\end{document}" << endl;

  return 0;
}
