#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include "Polynomial.h"
#include "Term.h"
#include "Coefficient.h"
#include "DoubleTerm.h"

using namespace std;

int main()
{

  ofstream texFile;
  texFile.open("Anharmonic_8.tex", fstream::trunc);
  texFile << "\\documentclass{article}"                                           << endl;
  texFile << "\\usepackage{longtable}"                                            << endl;
  texFile << "\\title{Anharmonic Group Elements as Generated by Machine}"         << endl;
  texFile << "\\author{Ed Rogers}"                                                << endl;
  texFile << "\\date{March 2011}"                                                 << endl;
  texFile << "\\begin{document}"                                                  << endl;
  texFile << "   \\maketitle"                                                     << endl;
									          
  texFile << "\\begin{center}"                                                    << endl;
  texFile << "\\begin{longtable}{lll}"                                            << endl;
  /* texFile << "\\textbf{Typed in by hand} & & \\textbf{Computed by machine} \\\\"  << endl; */
  /* texFile << "\\hline"                                                            << endl; */


  /* vector<Term> L0Terms; */
  /* L0Terms.push_back(Term("(1)")); */
  /* Polynomial L0(L0Terms); */

  vector<Term> L1Terms;
  L1Terms.push_back(Term("BA"));
  Polynomial L1(L1Terms);

  vector<Term> L2Terms;
  L2Terms.push_back(Term("lambda"));
  Polynomial L2(L2Terms);

  vector<Term> L3Terms;
  L3Terms.push_back(Term("lambda*BA"));
  Polynomial L3(L3Terms);

  vector<Term> L4Terms;
  L4Terms.push_back(Term("lambda*BBAA"));
  Polynomial L4(L4Terms);

  vector<Term> L5Terms;
  L5Terms.push_back(Term("lambda*BBBB"));
  L5Terms.push_back(Term("lambda*AAAA"));
  Polynomial L5(L5Terms);

  vector<Term> L6Terms;
  L6Terms.push_back(Term("lambda*BBBA"));
  L6Terms.push_back(Term("lambda*BAAA"));
  Polynomial L6(L6Terms);

  vector<Term> L7Terms;
  L7Terms.push_back(Term("lambda*BB"));
  L7Terms.push_back(Term("lambda*AA"));
  Polynomial L7(L7Terms);

  vector<Term> L8Terms;
  L8Terms.push_back(Term("lambda*BBBB"));
  L8Terms.push_back(Term("lambda*(-1)*AAAA"));
  Polynomial L8(L8Terms);

  vector<Term> L9Terms;
  L9Terms.push_back(Term("lambda*BBBA"));
  L9Terms.push_back(Term("lambda*(-1)*BAAA"));
  Polynomial L9(L9Terms);

  vector<Term> L10Terms;
  L10Terms.push_back(Term("lambda*BB"));
  L10Terms.push_back(Term("lambda*(-1)*AA"));
  Polynomial L10(L10Terms);

  vector<Term> L11Terms;
  L11Terms.push_back(Term("lambda^2"));
  Polynomial L11(L11Terms);

  vector<Term> L12Terms;
  L12Terms.push_back(Term("lambda^2*BA"));
  Polynomial L12(L12Terms);

  vector<Term> L13Terms;
  L13Terms.push_back(Term("lambda^2*BBAA"));
  Polynomial L13(L13Terms);

  vector<Term> L14Terms;
  L14Terms.push_back(Term("lambda^2*BBBAAA"));
  Polynomial L14(L14Terms);

  vector<Term> L15Terms;
  L15Terms.push_back(Term("lambda^2*BBBBBB"));
  L15Terms.push_back(Term("lambda^2*AAAAAA"));
  Polynomial L15(L15Terms);

  vector<Term> L16Terms;
  L16Terms.push_back(Term("lambda^2*BBBBBA"));
  L16Terms.push_back(Term("lambda^2*BAAAAA"));
  Polynomial L16(L16Terms);

  vector<Term> L17Terms;
  L17Terms.push_back(Term("lambda^2*BBBBAA"));
  L17Terms.push_back(Term("lambda^2*BBAAAA"));
  Polynomial L17(L17Terms);

  vector<Term> L18Terms;
  L18Terms.push_back(Term("lambda^2*BBBB"));
  L18Terms.push_back(Term("lambda^2*AAAA"));
  Polynomial L18(L18Terms);

  vector<Term> L19Terms;
  L19Terms.push_back(Term("lambda^2*BBBA"));
  L19Terms.push_back(Term("lambda^2*BAAA"));
  Polynomial L19(L19Terms);

  vector<Term> L20Terms;
  L20Terms.push_back(Term("lambda^2*BB"));
  L20Terms.push_back(Term("lambda^2*AA"));
  Polynomial L20(L20Terms);

  vector<Term> L21Terms;
  L21Terms.push_back(Term("lambda^2*BBBBBB"));
  L21Terms.push_back(Term("lambda^2*(-1)*AAAAAA"));
  Polynomial L21(L21Terms);

  vector<Term> L22Terms;
  L22Terms.push_back(Term("lambda^2*BBBBBA"));
  L22Terms.push_back(Term("lambda^2*(-1)*BAAAAA"));
  Polynomial L22(L22Terms);

  vector<Term> L23Terms;
  L23Terms.push_back(Term("lambda^2*BBBBAA"));
  L23Terms.push_back(Term("lambda^2*(-1)*BBAAAA"));
  Polynomial L23(L23Terms);

  vector<Term> L24Terms;
  L24Terms.push_back(Term("lambda^2*BBBB"));
  L24Terms.push_back(Term("lambda^2*(-1)*AAAA"));
  Polynomial L24(L24Terms);

  vector<Term> L25Terms;
  L25Terms.push_back(Term("lambda^2*BBBA"));
  L25Terms.push_back(Term("lambda^2*(-1)*BAAA"));
  Polynomial L25(L25Terms);

  vector<Term> L26Terms;
  L26Terms.push_back(Term("lambda^2*BB"));
  L26Terms.push_back(Term("lambda^2*(-1)*AA"));
  Polynomial L26(L26Terms);

  vector<Polynomial> Lambda1Polynomials;
  vector<Polynomial> Lambda2Polynomials;

  Lambda1Polynomials.push_back(L3);
  Lambda1Polynomials.push_back(L4);
  Lambda1Polynomials.push_back(L5);
  Lambda1Polynomials.push_back(L6);
  Lambda1Polynomials.push_back(L7);
  Lambda1Polynomials.push_back(L8);
  Lambda1Polynomials.push_back(L9);
  Lambda1Polynomials.push_back(L10);

  Lambda2Polynomials.push_back(L11);
  Lambda2Polynomials.push_back(L12);
  Lambda2Polynomials.push_back(L13);
  Lambda2Polynomials.push_back(L14);
  Lambda2Polynomials.push_back(L15);
  Lambda2Polynomials.push_back(L16);
  Lambda2Polynomials.push_back(L17);
  Lambda2Polynomials.push_back(L18);
  Lambda2Polynomials.push_back(L19);
  Lambda2Polynomials.push_back(L20);
  Lambda2Polynomials.push_back(L21);
  Lambda2Polynomials.push_back(L22);
  Lambda2Polynomials.push_back(L23);
  Lambda2Polynomials.push_back(L24);
  Lambda2Polynomials.push_back(L25);
  Lambda2Polynomials.push_back(L26);
  
  int numL1 = 3;
  for (vector<Polynomial>::iterator it1 = Lambda1Polynomials.begin();
       it1 != Lambda1Polynomials.end(); it1++)
    {
      int numL2 = 11;      
      for (vector<Polynomial>::iterator it2 = Lambda2Polynomials.begin();
	   it2 != Lambda2Polynomials.end(); it2++)
	{
	  Polynomial CommutatorResult = it1->commutedWith(*it2);
	  CommutatorResult.groupTerms();

	  if (CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size() > 0) 
	    {

	      int termsAtATime = 1;
	      int linesPrinted = 0;
	  
	      texFile << "$[L_{" << numL1 << "},L_{" << numL2 << "}]$ & = & $";
	      CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);

	      int termsToPrint = CommutatorResult.getTerms().size()+CommutatorResult.getDoubleTerms().size();
	      int totalLinesToPrint = termsToPrint/termsAtATime;
	      if (termsToPrint%termsAtATime != 0) totalLinesToPrint++;
	      if (linesPrinted < totalLinesToPrint)
		{
		  texFile << "$ \\\\*" << endl;
		}
	      else 
		{
		  texFile << "$ \\\\" << endl;
		}
	      while (linesPrinted < totalLinesToPrint)
		{
		  texFile << " & & $";
		  CommutatorResult.printTex(texFile,termsAtATime,linesPrinted++);
		  texFile << "$";
		  if (linesPrinted < totalLinesToPrint)
		    {
		      texFile << " \\\\*" << endl;
		    }
		  else 
		    {
		      texFile << " \\\\" << endl;
		    }
		}  
	    } 
	  else 
	    {
	      texFile << "$[L_{" << numL1 << "},L_{" << numL2 << "}]$ & = & $ 0 $ \\\\" << endl;
	    }
	  numL2++;
	}
      numL1++;
    }

  texFile << "\\end{longtable}"                                            << endl << endl;
  texFile << "\\end{center}"                                               << endl;

  texFile << "\\end{document}" << endl;

  return 0;
}
